//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Motors.rc
//
#define IDC_EDIT_XMIN                   3
#define IDD_ABOUTBOX                    100
#define IDD_STEPPERS_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDR_MOTORSTYPE                  129
#define ID_INDICATOR_ITER               129
#define IDD_OPTIONDLG                   130
#define IDR_DUMPTYPE                    130
#define IDR_ZOOMTYPE                    131
#define ID_INDICATOR_POS                132
#define ID_INDICATOR_AMOUNT             133
#define IDD_INIT                        134
#define IDD_POSITION                    135
#define IDD_SAVEDLG                     136
#define IDI_MOTORS                      137
#define IDC_REFRESH                     1001
#define IDC_PARK1                       1002
#define IDC_STATUS                      1003
#define IDC_EDIT_POS1                   1004
#define IDC_BREAK                       1005
#define IDC_GO1                         1006
#define IDC_EDIT_MOVE                   1007
#define IDC_GET                         1007
#define IDC_EDIT_GOTO1                  1008
#define IDC_SET                         1009
#define IDC_MV1                         1010
#define IDC_SET1                        1010
#define IDC_SET3                        1010
#define IDC_MV2                         1011
#define IDC_EDIT_SET1                   1011
#define IDC_MV3                         1012
#define IDC_MV4                         1013
#define IDC_MV5                         1014
#define IDC_MV6                         1015
#define IDC_MV7                         1016
#define IDC_MV8                         1017
#define IDC_EDIT_HORZL                  1018
#define IDC_EDIT_HORZR                  1019
#define IDC_READ1                       1022
#define IDC_STOP1                       1026
#define IDC_INIT1                       1027
#define IDC_EDIT_TO                     1029
#define IDC_EDIT_FROM                   1030
#define IDC_EDIT_STEP                   1031
#define IDC_SWEEP                       1032
#define IDC_EDIT_SS                     1034
#define IDC_EDIT_CS                     1035
#define IDC_EDIT_CHT                    1035
#define IDC_EDIT_ACC                    1036
#define IDC_VBEG                        1036
#define IDC_PROPERTY                    1038
#define IDC_EDIT_BASE                   1039
#define IDC_EDIT_SWS                    1039
#define IDC_EDIT_STATUS                 1040
#define IDC_DIR_BROWSE                  1040
#define IDC_EDIT_DATA                   1041
#define IDC_FILE_BROWSE                 1041
#define IDC_EDIT_TMO                    1042
#define IDC_EDIT_HTMO                   1043
#define IDC_GETPOS                      1044
#define IDC_SAVE                        1045
#define IDC_SETPOS                      1046
#define IDC_TRUNCATE                    1046
#define IDC_R1                          1048
#define IDC_R2                          1049
#define IDC_R3                          1050
#define IDC_R4                          1051
#define IDC_R5                          1052
#define IDC_R6                          1053
#define IDC_RASTERSCAN                  1054
#define IDC_EDIT_SS1                    1057
#define IDC_EDIT_CS1                    1058
#define IDC_EDIT_ACC1                   1059
#define IDC_EDIT_FROM1                  1060
#define IDC_EDIT_TO1                    1061
#define IDC_EDIT_STEP1                  1062
#define IDC_EDIT_LIM1                   1064
#define IDC_EDIT_LIM2                   1065
#define IDC_WAITFOR                     1077
#define IDC_EDIT_BACKLASH               1078
#define IDC_FASTMOTOR                   1079
#define IDC_MOTORTAB                    1080
#define IDC_BRUUT                       1081
#define IDC_EDIT_FILE                   1082
#define IDC_EDIT_DIR                    1083
#define IDC_EDIT_NOW                    1086
#define IDC_MOTOR                       1087
#define IDC_RSCAN                       1088
#define IDC_SSTEP                       1089
#define IDC_STO                         1090
#define IDC_P1                          1091
#define IDC_P10                         1092
#define IDC_P100                        1093
#define IDC_P1000                       1094
#define IDC_P10000                      1095
#define IDC_M1                          1096
#define IDC_M10                         1097
#define IDC_M100                        1098
#define IDC_M1000                       1099
#define IDC_M10000                      1100
#define IDC_SFROM                       1101
#define IDC_RUUT                        1101
#define IDC_AUTONORM                    1102
#define IDC_EDIT_YMIN                   1103
#define IDC_SHOW                        1104
#define IDC_SHOWN                       1105
#define IDC_ZERONORM                    1105
#define IDC_EDIT_SPECTRA                1107
#define IDC_EDIT_YMAX                   1109
#define IDC_EDIT_CURVES                 1109
#define IDC_EDIT_START                  1110
#define IDC_EDIT_XMAX                   1110
#define IDC_EDIT_AMOUNT                 1111
#define IDC_XGRID                       1112
#define IDC_YGRID                       1113
#define IDC_XYNORM                      1114
#define IDC_YNORM                       1115
#define IDC_XNORM                       1116
#define IDC_REDRAW                      1117
#define IDC_SETUP                       1120
#define IDC_SAVEALL                     1121
#define IDC_RESTORE                     1122
#define IDC_Detector                    1125
#define IDC_REGIME                      1126
#define IDC_BACKGROUND                  1128
#define IDC_TEMPERATURE                 1129
#define IDC_BCKGR                       1130
#define IDC_ROI                         1131
#define IDC_HBEG                        1132
#define IDC_HEND                        1133
#define IDC_VEND                        1135
#define IDC_BUTTON1                     1136
#define IDC_BUTTON2                     1137
#define IDC_585                         1138
#define IDC_coeff                       1139
#define IDC_EDIT2                       1140

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
